- id: missing-build-tags
  name: Check for missing build tags
  description: This hook checks for missing build tags
  entry: gotaglint
  language: golang
  types: [file, go]
  pass_filenames: false
  require_serial: true
